# Site settings
title: Sonder's TV
SEOTitle: Sonder的TV | Sonder's TV
header-img: img/post-bg-desk.jpg
email: wait3124@gmail.com
description: "Every failure is leading towards success."
keyword: "None"
url: "https://tv.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/Smilemon/tv.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Goals determine what you going to be!"
sidebar-avatar: /img/smile.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`
